// <auto-generated />
using System;
using HaverGroupProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HaverGroupProject.Data.HaverMigrations
{
    [DbContext(typeof(HaverContext))]
    [Migration("20250119181033_IntToString")]
    partial class IntToString
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("HaverGroupProject.Models.Customer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("HaverGroupProject.Models.OperationsSchedule", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AirSeal")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BaseFrame")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CoatingLining")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CustomerID")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("DeliveryDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Disassebmly")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExtSalesOrdNum")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("InstalledMedia")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("KickoffMeeting")
                        .HasColumnType("TEXT");

                    b.Property<string>("MachineDesc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("PODueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PONum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PackageReleaseName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ReleaseApprovalDrawing")
                        .HasColumnType("TEXT");

                    b.Property<int>("SalesOrdNum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SerialNum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("SparePartsSpareMedia")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VendorID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("VendorID");

                    b.ToTable("OperationsSchedules");
                });

            modelBuilder.Entity("HaverGroupProject.Models.Vendor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("VendorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Vendors");
                });

            modelBuilder.Entity("HaverGroupProject.Models.OperationsSchedule", b =>
                {
                    b.HasOne("HaverGroupProject.Models.Customer", "Customer")
                        .WithMany("OperationsSchedules")
                        .HasForeignKey("CustomerID");

                    b.HasOne("HaverGroupProject.Models.Vendor", "Vendor")
                        .WithMany("OperationsSchedules")
                        .HasForeignKey("VendorID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Customer");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("HaverGroupProject.Models.Customer", b =>
                {
                    b.Navigation("OperationsSchedules");
                });

            modelBuilder.Entity("HaverGroupProject.Models.Vendor", b =>
                {
                    b.Navigation("OperationsSchedules");
                });
#pragma warning restore 612, 618
        }
    }
}
