// <auto-generated />
using System;
using HaverGroupProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HaverGroupProject.Data.HaverMigrations
{
    [DbContext(typeof(HaverContext))]
    [Migration("20250127041844_createDatabase")]
    partial class createDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("HaverGroupProject.Models.Customer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomerAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerContactName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("HaverGroupProject.Models.OperationsSchedule", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CustomerID")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("DeliveryDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExtSalesOrdNum")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("KickoffMeeting")
                        .HasColumnType("TEXT");

                    b.Property<string>("MachineDesc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("PODueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PONum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PackageReleaseName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ReleaseApprovalDrawing")
                        .HasColumnType("TEXT");

                    b.Property<int>("SalesOrdNum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SerialNum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("VendorID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("VendorID");

                    b.ToTable("OperationsSchedules");
                });

            modelBuilder.Entity("HaverGroupProject.Models.OperationsScheduleVendor", b =>
                {
                    b.Property<int>("VendorID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OperationsScheduleID")
                        .HasColumnType("INTEGER");

                    b.HasKey("VendorID", "OperationsScheduleID");

                    b.HasIndex("OperationsScheduleID");

                    b.ToTable("OperationsScheduleVendors");
                });

            modelBuilder.Entity("HaverGroupProject.Models.Vendor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("VendorAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VendorContactName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VendorEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VendorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VendorPhone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Vendors");
                });

            modelBuilder.Entity("HaverGroupProject.Models.OperationsSchedule", b =>
                {
                    b.HasOne("HaverGroupProject.Models.Customer", "Customer")
                        .WithMany("OperationsSchedules")
                        .HasForeignKey("CustomerID");

                    b.HasOne("HaverGroupProject.Models.Vendor", "Vendor")
                        .WithMany("OperationsSchedules")
                        .HasForeignKey("VendorID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Customer");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("HaverGroupProject.Models.OperationsScheduleVendor", b =>
                {
                    b.HasOne("HaverGroupProject.Models.OperationsSchedule", "OperationsSchedule")
                        .WithMany("OperationsScheduleVendors")
                        .HasForeignKey("OperationsScheduleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HaverGroupProject.Models.Vendor", "Vendor")
                        .WithMany("OperationsScheduleVendors")
                        .HasForeignKey("VendorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OperationsSchedule");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("HaverGroupProject.Models.Customer", b =>
                {
                    b.Navigation("OperationsSchedules");
                });

            modelBuilder.Entity("HaverGroupProject.Models.OperationsSchedule", b =>
                {
                    b.Navigation("OperationsScheduleVendors");
                });

            modelBuilder.Entity("HaverGroupProject.Models.Vendor", b =>
                {
                    b.Navigation("OperationsScheduleVendors");

                    b.Navigation("OperationsSchedules");
                });
#pragma warning restore 612, 618
        }
    }
}
