// <auto-generated />
using System;
using HaverGroupProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HaverGroupProject.Data.HaverMigrations
{
    [DbContext(typeof(HaverContext))]
    partial class HaverContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("HaverGroupProject.Models.Customer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomerAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerContactName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("HaverGroupProject.Models.Engineer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EngEmail")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("EngFirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("EngLastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("EngMiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("EngPhone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.HasKey("ID");

                    b.ToTable("Engineers");
                });

            modelBuilder.Entity("HaverGroupProject.Models.MachineDescription", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<string>("Deck")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<bool>("NamePlateOrdered")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NameplateRecieved")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("MachineDescriptions");
                });

            modelBuilder.Entity("HaverGroupProject.Models.OperationsSchedule", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CustomerID")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("DeliveryDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("EngineerID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExtSalesOrdNum")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("KickoffMeeting")
                        .HasColumnType("TEXT");

                    b.Property<string>("MachineDesc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MachineDescriptionID")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("PODueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PONum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PackageReleaseName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ReleaseApprovalDrawing")
                        .HasColumnType("TEXT");

                    b.Property<int>("SalesOrdNum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SerialNum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("VendorID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("EngineerID");

                    b.HasIndex("MachineDescriptionID");

                    b.HasIndex("VendorID");

                    b.ToTable("OperationsSchedules");
                });

            modelBuilder.Entity("HaverGroupProject.Models.Vendor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("VendorAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VendorContactName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VendorEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VendorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VendorPhone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Vendors");
                });

            modelBuilder.Entity("HaverGroupProject.Models.OperationsSchedule", b =>
                {
                    b.HasOne("HaverGroupProject.Models.Customer", "Customer")
                        .WithMany("OperationsSchedules")
                        .HasForeignKey("CustomerID");

                    b.HasOne("HaverGroupProject.Models.Engineer", "Engineer")
                        .WithMany("OperationsSchedules")
                        .HasForeignKey("EngineerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HaverGroupProject.Models.MachineDescription", "MachineDescription")
                        .WithMany("OperationsSchedules")
                        .HasForeignKey("MachineDescriptionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HaverGroupProject.Models.Vendor", "Vendor")
                        .WithMany("OperationsSchedules")
                        .HasForeignKey("VendorID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Customer");

                    b.Navigation("Engineer");

                    b.Navigation("MachineDescription");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("HaverGroupProject.Models.Customer", b =>
                {
                    b.Navigation("OperationsSchedules");
                });

            modelBuilder.Entity("HaverGroupProject.Models.Engineer", b =>
                {
                    b.Navigation("OperationsSchedules");
                });

            modelBuilder.Entity("HaverGroupProject.Models.MachineDescription", b =>
                {
                    b.Navigation("OperationsSchedules");
                });

            modelBuilder.Entity("HaverGroupProject.Models.Vendor", b =>
                {
                    b.Navigation("OperationsSchedules");
                });
#pragma warning restore 612, 618
        }
    }
}
