// <auto-generated />
using System;
using HaverGroupProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HaverGroupProject.Data.HaverMigrations
{
    [DbContext(typeof(HaverContext))]
    partial class HaverContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("HaverGroupProject.Models.Customer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustContactFirst")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CustContactLastName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerAddress")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("CustomerArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomerEmail")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("HaverGroupProject.Models.Employee", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("HaverGroupProject.Models.Engineer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EngEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("EngFirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("EngLastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("EngMiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("EngPhone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Engineers");
                });

            modelBuilder.Entity("HaverGroupProject.Models.HaverGantt", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ApprvDwgRecvd")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EngineerID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GanttNotes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("MachineDescriptionID")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Progress")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PromiseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PurchaseOrderNum")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VendorID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("EngineerID");

                    b.HasIndex("MachineDescriptionID");

                    b.HasIndex("VendorID");

                    b.ToTable("HaverGantts");
                });

            modelBuilder.Entity("HaverGroupProject.Models.MachineDescription", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AirSeal")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BaseFrame")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<bool>("CoatingLining")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Deck")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Disassembly")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("InstalledMedia")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NamePlateOrdered")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NameplateRecieved")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("TEXT");

                    b.Property<bool>("SpareParts")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SparePartsSpareMedia")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("MachineDescriptions");
                });

            modelBuilder.Entity("HaverGroupProject.Models.Note", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActualAssembHours")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActualReworkHours")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BudgetAssembHrs")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OperationsScheduleID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OtherComments")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreOrder")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("HaverGroupProject.Models.OperationsSchedule", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ApprovalDrawingExpected")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ApprovalDrawingReleased")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ApprovalDrawingReturned")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CustomerID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EngineerID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EngineerPackageExpected")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EngineerPackageReleased")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("KickoffMeeting")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MachineDescriptionID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NCRRaised")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NoteID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PONum")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PUrchaseOrderRecieved")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PreOrderExpected")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PreOrderReleased")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductionOrderNumber")
                        .HasColumnType("TEXT");

                    b.Property<double?>("ProgressApprovalDrawing")
                        .HasColumnType("REAL");

                    b.Property<double?>("ProgressEngineerPackage")
                        .HasColumnType("REAL");

                    b.Property<double?>("ProgressPreOrder")
                        .HasColumnType("REAL");

                    b.Property<double?>("ProgressPurchaseOrder")
                        .HasColumnType("REAL");

                    b.Property<double?>("ProgressReadinesstoShip")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("PurchaseOrderDueDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PurchaseOrderExpected")
                        .HasColumnType("TEXT");

                    b.Property<bool>("QIComplete")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ReadinessToShipActual")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReadinessToShipExpected")
                        .HasColumnType("TEXT");

                    b.Property<int>("SalesOrdNum")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Value")
                        .HasColumnType("REAL");

                    b.Property<int?>("VendorID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("EngineerID");

                    b.HasIndex("MachineDescriptionID");

                    b.HasIndex("NoteID")
                        .IsUnique();

                    b.HasIndex("VendorID");

                    b.ToTable("OperationsSchedules");
                });

            modelBuilder.Entity("HaverGroupProject.Models.OperationsScheduleMachine", b =>
                {
                    b.Property<int>("MachineDescriptionID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OperationsScheduleID")
                        .HasColumnType("INTEGER");

                    b.HasKey("MachineDescriptionID", "OperationsScheduleID");

                    b.HasIndex("OperationsScheduleID");

                    b.ToTable("OperationsScheduleMachines");
                });

            modelBuilder.Entity("HaverGroupProject.Models.OperationsScheduleVendor", b =>
                {
                    b.Property<int>("VendorID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OperationsScheduleID")
                        .HasColumnType("INTEGER");

                    b.HasKey("VendorID", "OperationsScheduleID");

                    b.HasIndex("OperationsScheduleID");

                    b.ToTable("OperationsScheduleVendors");
                });

            modelBuilder.Entity("HaverGroupProject.Models.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PushAuth")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("PushEndpoint")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("PushP256DH")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeID");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("HaverGroupProject.Models.Vendor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("VendorAddress")
                        .HasColumnType("TEXT");

                    b.Property<bool>("VendorArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VendorContactName")
                        .HasColumnType("TEXT");

                    b.Property<string>("VendorEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("VendorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VendorPhone")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Vendors");
                });

            modelBuilder.Entity("HaverGroupProject.Models.HaverGantt", b =>
                {
                    b.HasOne("HaverGroupProject.Models.Customer", "Customer")
                        .WithMany("HaverGantts")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HaverGroupProject.Models.Engineer", "Engineer")
                        .WithMany("HaverGantts")
                        .HasForeignKey("EngineerID");

                    b.HasOne("HaverGroupProject.Models.MachineDescription", "MachineDescription")
                        .WithMany("HaverGantts")
                        .HasForeignKey("MachineDescriptionID");

                    b.HasOne("HaverGroupProject.Models.Vendor", "Vendor")
                        .WithMany("HaverGantts")
                        .HasForeignKey("VendorID");

                    b.Navigation("Customer");

                    b.Navigation("Engineer");

                    b.Navigation("MachineDescription");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("HaverGroupProject.Models.OperationsSchedule", b =>
                {
                    b.HasOne("HaverGroupProject.Models.Customer", "Customer")
                        .WithMany("OperationsSchedule")
                        .HasForeignKey("CustomerID");

                    b.HasOne("HaverGroupProject.Models.Engineer", "Engineer")
                        .WithMany("OperationsSchedules")
                        .HasForeignKey("EngineerID");

                    b.HasOne("HaverGroupProject.Models.MachineDescription", "MachineDescription")
                        .WithMany("OperationsSchedules")
                        .HasForeignKey("MachineDescriptionID");

                    b.HasOne("HaverGroupProject.Models.Note", "Note")
                        .WithOne("OperationsSchedule")
                        .HasForeignKey("HaverGroupProject.Models.OperationsSchedule", "NoteID");

                    b.HasOne("HaverGroupProject.Models.Vendor", "Vendor")
                        .WithMany("OperationsSchedules")
                        .HasForeignKey("VendorID");

                    b.Navigation("Customer");

                    b.Navigation("Engineer");

                    b.Navigation("MachineDescription");

                    b.Navigation("Note");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("HaverGroupProject.Models.OperationsScheduleMachine", b =>
                {
                    b.HasOne("HaverGroupProject.Models.MachineDescription", "MachineDescription")
                        .WithMany("OperationsScheduleMachines")
                        .HasForeignKey("MachineDescriptionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HaverGroupProject.Models.OperationsSchedule", "OperationsSchedule")
                        .WithMany("OperationsScheduleMachines")
                        .HasForeignKey("OperationsScheduleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MachineDescription");

                    b.Navigation("OperationsSchedule");
                });

            modelBuilder.Entity("HaverGroupProject.Models.OperationsScheduleVendor", b =>
                {
                    b.HasOne("HaverGroupProject.Models.OperationsSchedule", "OperationsSchedule")
                        .WithMany("OperationsScheduleVendors")
                        .HasForeignKey("OperationsScheduleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HaverGroupProject.Models.Vendor", "Vendor")
                        .WithMany("OperationsScheduleVendors")
                        .HasForeignKey("VendorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OperationsSchedule");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("HaverGroupProject.Models.Subscription", b =>
                {
                    b.HasOne("HaverGroupProject.Models.Employee", "Employee")
                        .WithMany("Subscriptions")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HaverGroupProject.Models.Customer", b =>
                {
                    b.Navigation("HaverGantts");

                    b.Navigation("OperationsSchedule");
                });

            modelBuilder.Entity("HaverGroupProject.Models.Employee", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("HaverGroupProject.Models.Engineer", b =>
                {
                    b.Navigation("HaverGantts");

                    b.Navigation("OperationsSchedules");
                });

            modelBuilder.Entity("HaverGroupProject.Models.MachineDescription", b =>
                {
                    b.Navigation("HaverGantts");

                    b.Navigation("OperationsScheduleMachines");

                    b.Navigation("OperationsSchedules");
                });

            modelBuilder.Entity("HaverGroupProject.Models.Note", b =>
                {
                    b.Navigation("OperationsSchedule");
                });

            modelBuilder.Entity("HaverGroupProject.Models.OperationsSchedule", b =>
                {
                    b.Navigation("OperationsScheduleMachines");

                    b.Navigation("OperationsScheduleVendors");
                });

            modelBuilder.Entity("HaverGroupProject.Models.Vendor", b =>
                {
                    b.Navigation("HaverGantts");

                    b.Navigation("OperationsScheduleVendors");

                    b.Navigation("OperationsSchedules");
                });
#pragma warning restore 612, 618
        }
    }
}
